---
title: "FLAME data description"
output: html_document
date: "2026-07-31"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Aim


## Description


```{r}
library(dplyr)
library(tidyr)
library(magrittr)
library(stringr)
library(geosphere)
library(ggplot2)
library(cowplot)
library(OpenStreetMap)
library(RColorBrewer)
library(patchwork)
library(ggspatial)
```

### Analysis folder


```{r 'Analysis folder'}
control_baseline_individuals = read.csv('data/analysis/control_baseline_individuals.csv')
control_malaria_cases_by_person = read.csv('data/analysis/control_malaria_cases_by_person.csv')
```


```{r 'Normalize indv., hh., and village ids and extract gps coordinates'}

options(digits = 16)


control_malaria_cases_by_person %<>% 
  mutate(
    base_ind_code = case_when( # Make every indv id to have 5 digits
      nchar(base_ind_code) == 4 ~ as.character(paste0(0, base_ind_code)),
      nchar(base_ind_code) == 5 ~ as.character(base_ind_code)),
    unihh_p = case_when( # Make every hh id to have 5 digits
      nchar(unihh_p) == 4 ~ as.character(paste0(0, unihh_p)),
      nchar(unihh_p) == 5 ~ as.character(unihh_p)
    ),
    
    base_ind_code = case_when( # Generate an indv. id for indv no enrolled in the baseline study
      is.na(base_ind_code) ~ paste0('c', unihh_p),
      .default = base_ind_code
    ),
    
    longitude = as.double(gsub('(c\\(|,.+$)', '', geometry)), # Extract longitude
    latitude = as.double(gsub('(^.+,|\\)$)', '', geometry)), # Extract latitude
    
    village_id = case_when( # Extract village_id (2 digits per site)
      nchar(base_ind_code) == 5 ~ substr(base_ind_code, 1, 2),
      .default = substr(base_ind_code, 2, 3)
      )
    )

```

```{r 'Add village names'}
village_sumary = control_baseline_individuals %>% 
  summarise(nSamples = n(), .by = c(community, locality)) %>%
  dplyr::rename('village_id' = 'community', 'village' = 'locality') %>%
  mutate(village_id = case_when(
           nchar(as.character(village_id)) == 1 ~ paste0(0, as.character(village_id)),
           .default = as.character(village_id)
           )
        )

control_malaria_cases_by_person = left_join(control_malaria_cases_by_person, village_sumary[,1:2], by = join_by('village_id' == 'village_id'))


```



```{r 'Transform data to long format'}
malaria_cases_by_person_long = control_malaria_cases_by_person %>% select(-geometry) %>% pivot_longer(cols = all_of(ends_with('date')), names_to = 'episode', values_to = 'date') %>% filter(!is.na(date))

```


```{r 'Group samples by year quarters'}
malaria_cases_by_person_long %<>% mutate(
  date = as.Date(date),
  year_quarter = paste0(gsub('-.+$', '', date), '-', quarters(date)))
```



```{r 'Geographic distance between households'}

hh_table = 
  malaria_cases_by_person_long %>% 
  select(unihh_p, longitude, latitude, village) %>% 
  filter(!is.na(unihh_p)) %>% 
  summarise(unihh_p = unique(unihh_p),
            longitude = mean(longitude),
            latitude = mean(latitude),
            village = unique(village),
            .by = unihh_p
            ) %>%
  arrange(unihh_p)



hh_comb = data.frame(t(combn(hh_table$unihh_p, 2)))

colnames(hh_comb) = c('hh_i', 'hh_j')

hh_comb = left_join(hh_comb, hh_table, by = join_by('hh_i' == 'unihh_p'))

colnames(hh_comb) = c('hh_i', 'hh_j', 'longitude_i', 'latitude_i','village_i')

hh_comb = left_join(hh_comb, hh_table, by = join_by('hh_j' == 'unihh_p'))

colnames(hh_comb) = c('hh_i', 'hh_j', 'longitude_i', 'latitude_i','village_i', 'longitude_j', 'latitude_j','village_j')

hh_comb %<>% 
  mutate(scale = case_when(
    village_i == village_j ~ 'Within',
    .default = 'Between')
  )


hh_comb %<>% 
  mutate(geo_dist = distHaversine(p1 = cbind(longitude_i, latitude_i),
                                  p2 = cbind(longitude_j, latitude_j)
                                  ))

```

```{r, fig.width= 5, fig.height=6}
hh_comb %>%
  filter(scale == 'Within') %>%
  ggplot(aes(x = geo_dist)) +
  geom_histogram() + 
  facet_grid(village_i ~ ., scales = 'free')+
  theme(strip.text.y = element_text(angle = 0))

```




```{r 'plot houshold in villages'}

max_long = hh_table %>%
  select(longitude) %>%
  unlist() %>%
  max(na.rm = T)

min_long = hh_table %>%
  select(longitude) %>%
  unlist() %>%
  min(na.rm = T)

max_latd = hh_table %>%
  select(latitude) %>%
  unlist() %>%
  max(na.rm = T)

min_latd = hh_table %>%
  select(latitude) %>%
  unlist() %>%
  min(na.rm = T)

osm <- openmap(c(min_latd - 0.025, min_long - 0.025), 
               c(max_latd + 0.025, max_long + 0.025), 
               zoom = NULL,
               type = "osm", 
               mergeTiles = TRUE)

osm <- openproj(osm, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
    
village_palette = col_vector[1:length(unique(hh_table$village))]

get_longitud = function(lon_start, lon_end, lat, ref, presision = 0.0000001){

  scale_ref = distHaversine(p1 = c(lon_start, lat), p2 = c(lon_end, lat))

  while(scale_ref > ref){
  lon_start = lon_start + presision
  scale_ref = distHaversine(p1 = c(lon_start, lat), p2 = c(lon_end, lat))
  }
  
  return(lon_start)
}

lon1.1 = -73.4
lon2.1 = -73.3
lat.1 = -4.25
lon1.1_c1 = get_longitud(lon_start = lon1.1,
             lon_end =  lon2.1,
             lat = lat.1, ref = 10000, presision = 0.0000001)

map_1 = autoplot.OpenStreetMap(osm, alpha =.5) + 
  geom_point(data = hh_table,
         aes(x = longitude, y = latitude, color = village), shape = 16, size = 2) +
  scale_color_manual(values = c(village_palette[-15], 'black'))+
  scale_x_continuous(breaks = seq(-73.9, -73.3, .1), labels = round(seq(-73.9, -73.3, .1), 1)) +
  theme_minimal() + 
  geom_segment(aes(x = lon1.1_c1, xend = lon2.1, y = lat.1), size = 2) + 
  annotate('text', x = (lon1.1_c1 + lon2.1)/2 , y = lat.1 + .02, label = '10 km') +
  labs(x = 'Longitude',
       y = 'Latitude',
       color = 'Village')


max_long_02 = hh_table %>%
  filter(village == 'ZUNGARO COCHA') %>%
  select(longitude) %>%
  unlist() %>%
  max(na.rm = T)

min_long_02 = hh_table %>%
  filter(village == 'ZUNGARO COCHA') %>%
  select(longitude) %>%
  unlist() %>%
  min(na.rm = T)

max_latd_02 = hh_table %>%
  filter(village == 'ZUNGARO COCHA') %>%
  select(latitude) %>%
  unlist() %>%
  max(na.rm = T)

min_latd_02 = hh_table %>%
  filter(village == 'ZUNGARO COCHA') %>%
  select(latitude) %>%
  unlist() %>%
  min(na.rm = T)

osm_02 <- openmap(c(min_latd_02 - 0.005, min_long_02 - 0.005), 
               c(max_latd_02 + 0.005, max_long_02 + 0.005), 
               zoom = NULL,
               type = "osm", 
               mergeTiles = TRUE)

osm_02 <- openproj(osm_02, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")


lon1.2 = -73.39
lon2.2 = -73.35
lat.2 = -3.87
lon1.2_c = get_longitud(lon_start = lon1.2,
             lon_end =  lon2.2,
             lat = lat.2, ref = 1000, presision = 0.0000001)

map_2 = autoplot.OpenStreetMap(osm_02, alpha =.5) + 
  geom_point(data = hh_table %>% filter(village == 'ZUNGARO COCHA'),
         aes(x = longitude, y = latitude), shape = 16, size = 2, color = 'black') +
  geom_segment(aes(x = lon1.2_c, xend = lon2.2, y = lat.2), size = 2) + 
  annotate('text', x = (lon1.2_c + lon2.2)/2 , y = lat.2 + .005, label = '1 km') +
  theme_bw() +
  theme(axis.title = element_blank(),
        axis.text = element_blank(),
        title = element_text(size = 9)) +
  labs(title = 'Zungaro Cocha')


map_1 +
  inset_element(map_2, left = 0, bottom = .6, right = .4, top = 1)

```


```{r 'Number of positive samples per individual', fig.width= 4, fig.height= 5}
malaria_cases_by_person_long %<>% filter(!is.na(date) & !is.na(longitude))


malaria_cases_by_person_long %<>% 
  reframe(unihh_p = unihh_p,
          episode = episode,
          date = date, 
          longitude = longitude,
          latitude = latitude,
          village_id = village_id,
          village = village,
          samples_per_indv = n(), .by = base_ind_code)


malaria_cases_by_person_long %>%
  filter(episode == 'first_date') %>%
  ggplot(aes(x = samples_per_indv)) +
  geom_histogram() +
  facet_grid(village ~ ., scales = 'free') +
  scale_x_continuous(breaks = 1:10)+
  theme(strip.text.y = element_text(angle = 0))


```


```{r 'Time to previous episode', fig.width= 7, fig.height= 7}

malaria_cases_by_person_long %<>% arrange(base_ind_code, date)

malaria_cases_by_person_long$time2nextepisode = NA
malaria_cases_by_person_long$time2previousepisode = NA
malaria_cases_by_person_long$time2firstepisode = NA

for(indv in unique(malaria_cases_by_person_long$base_ind_code)){
  
  indv_data = malaria_cases_by_person_long %>% filter(base_ind_code == indv)
  
  if(nrow(indv_data) > 1){
    malaria_cases_by_person_long[malaria_cases_by_person_long$base_ind_code == indv,][['time2nextepisode']] = c(as.numeric(indv_data$date[-1] - indv_data$date[-nrow(indv_data)]), 0)
    malaria_cases_by_person_long[malaria_cases_by_person_long$base_ind_code == indv,][['time2previousepisode']] = c(0, as.numeric(indv_data$date[-1] - indv_data$date[-nrow(indv_data)]))
    malaria_cases_by_person_long[malaria_cases_by_person_long$base_ind_code == indv,][['time2firstepisode']] = c(0, as.numeric(indv_data$date[-1] - indv_data$date[1]))
  }
}

malaria_cases_by_person_long %>%
  filter(episode != 'first_date') %>%
  ggplot(aes(x = time2previousepisode)) +
  geom_histogram(binwidth = 7)+
  facet_grid(village ~ ., scales = 'free') +
  theme(strip.text.y = element_text(angle = 0))

```


```{r 'Time to previous episode (0 - 42 days)', fig.width= 7, fig.height= 7}
malaria_cases_by_person_long %>%
  filter(episode != 'first_date') %>%
  ggplot(aes(x = time2previousepisode)) +
  geom_histogram(binwidth = 1)+
  scale_x_continuous(limits = c(0, 42), breaks = seq(0, 42, 7))+
  facet_grid(village ~ ., scales = 'free') +
  theme(strip.text.y = element_text(angle = 0))

```

```{r 'Generate unique sample_id for each sample of each participant'}
malaria_cases_by_person_long$sample_id = NA


for(indv in unique(malaria_cases_by_person_long$base_ind_code)){
  
  nsamples = unique(malaria_cases_by_person_long[malaria_cases_by_person_long$base_ind_code == indv,][['samples_per_indv']])
  
  sample_ids = ifelse(nchar(1:nsamples) == 1, as.character(paste0(0, 1:nsamples)), as.character(1:nsamples))
  
  malaria_cases_by_person_long[malaria_cases_by_person_long$base_ind_code == indv,][['sample_id']] = paste0(indv, sample_ids)
  
}

```

```{r 'Time difference between all cases'}

sample_comb = data.frame(t(combn(malaria_cases_by_person_long %>% arrange(date) %>% select(sample_id) %>% unlist(), 2)))

colnames(sample_comb) = c('sample_i', 'sample_j')

sample_comb = 
  left_join(
    sample_comb,
    malaria_cases_by_person_long %>% 
      select(sample_id, base_ind_code, unihh_p, date, village_id, village, longitude, latitude),
    by = join_by('sample_i' == 'sample_id'))

sample_comb %<>% 
  dplyr::rename('indv_i' = 'base_ind_code', 
                'hh_i' = 'unihh_p', 
                'date_i' = 'date',
                'village_id_i' = 'village_id', 
                'village_i' = 'village', 
                'long_i' = 'longitude', 
                'lat_i' = 'latitude')

sample_comb = 
  left_join(
    sample_comb,
    malaria_cases_by_person_long %>% 
      select(sample_id, base_ind_code, unihh_p, date, village_id, village, longitude, latitude),
    by = join_by('sample_j' == 'sample_id'))

sample_comb %<>% 
  dplyr::rename('indv_j' = 'base_ind_code', 
                'hh_j' = 'unihh_p', 
                'date_j' = 'date',
                'village_id_j' = 'village_id', 
                'village_j' = 'village', 
                'long_j' = 'longitude', 
                'lat_j' = 'latitude')

sample_comb %<>% mutate(
  year_quarter_i = paste0(gsub('-.+$', '', date_i), '-', quarters(as.Date(date_i))),
  year_quarter_j = paste0(gsub('-.+$', '', date_j), '-', quarters(as.Date(date_j)))
)

sample_comb %<>% 
  mutate(scale = case_when(
    village_id_i == village_id_j ~ 'Within',
    .default = 'Between')
  )

sample_comb %<>% mutate(
  date_i = as.Date(date_i),
  date_j = as.Date(date_j),
  timedist = as.numeric(date_j - date_i))


sample_comb %<>% mutate(
  geodist = distHaversine(p1 = cbind(long_i, lat_i),
                          p2 = cbind(long_j, lat_j)))



```


```{r 'function for identifying clusters in network'}

get_network_clusters = 
  function(
    pairwise_relatedness,
    variable = 'rhat',
    threshold = 1,
    cols = c("sample_i", "sample_j"),
    rhat_formula = "timedist >= 16 & timedist <= 28 & geodist <= 750",
    metadata,
    sample_id = 'sample_id'){
    
    library(igraph)
    if(!require(GGally)){
      install.packages("GGally")
      library(GGally)
    }else{library(GGally)}
    
    if(!require(network)){
      install.packages("network")
      library(network)
    }else{library(network)}
    
    if(!require(sna)){
      install.packages("sna")
      library(sna)
    }else{library(sna)}
    
    if(!require(ggnet)){
      devtools::install_github("briatte/ggnet")
      library(ggnet)
    }else{library(ggnet)}
    
    library(S4Vectors)
    
    library(parallel)
    library(doMC)
    
    registerDoMC(detectCores()-1)
    
    
    pairwise_relatedness_l = 
      pairwise_relatedness[pairwise_relatedness[[cols[1]]] %in% metadata[[sample_id]] &
                             pairwise_relatedness[[cols[2]]] %in% metadata[[sample_id]]
                           ,
                           ]
    
    print('Defining edges ...')
    
    edges_start = Sys.time()
    
    if(!(variable %in% colnames(pairwise_relatedness_l))){
      
      conditions = unlist(strsplit(rhat_formula, '( & | \\| )'))
      
      rhat_formula_c = rhat_formula
      
      for(condition in conditions){
        
        temp_var = str_extract(condition, '([A-z]|\\.|_)+')
        temp_rep = gsub(temp_var, paste0("pairwise_relatedness_l[['", temp_var, "']]"), condition)
        
        rhat_formula_c = gsub(condition, temp_rep, rhat_formula_c)
          
      }
      
      pairwise_relatedness_l[[variable]] = 0
      
      pairwise_relatedness_l[eval(parse(text = rhat_formula_c)),
                             ][[variable]] = 1
      
    }
    
    selected_edges = pairwise_relatedness_l[pairwise_relatedness_l[[variable]] >= threshold,][,cols]
    
    edges = foreach(edge = 1:nrow(selected_edges), .combine = 'c') %dopar% {
      
      unlist(selected_edges[edge,])
    }
    
    sample_list = unique(unlist(pairwise_relatedness_l[,cols]))
    
    isolates = sample_list[!(sample_list %in% unique(edges))]
    
    edges_end = Sys.time()
    print('Identification of samples conected by edges and singletons took:')
    print(edges_end - edges_start)
    
    
    print('Creating network object ...')
    
    network_start = Sys.time()
    network_object = make_graph(edges = edges, isolates = isolates, directed=T)
    network_end = Sys.time()
    
    print('Generiation of the network object took: ')
    print(network_end - network_start)
    
    
    print('Identifying clusters in network ...')
    
    clusters_start = Sys.time()
    clusters = NULL
    for(node in 1:length(network_object)){
      
      # Set of samples linked with the node
      set_of_samples = c(names(network_object[[node]]), names(network_object[[node]][[1]]))
      
      proportion_of_samples_in_the_cluster = sapply(clusters, function(cluster){
        sum(set_of_samples %in% cluster)/length(set_of_samples)
      })
      
      cluster = which(proportion_of_samples_in_the_cluster > 0 & proportion_of_samples_in_the_cluster < 1 )
      
      if(length(cluster) == 1){
        
        clusters[[paste0('Cluster_', cluster)]] =
          c(clusters[[paste0('Cluster_', cluster)]],
            set_of_samples[!(set_of_samples %in% clusters[[paste0('Cluster_', cluster)]])]
          )
        
      }else if(length(cluster) > 1){
        # Combine clusters
        merged_cluster = unlist(clusters[cluster])
        
        names(merged_cluster) = NULL
        
        merged_cluster = c(merged_cluster,
                           set_of_samples[!(set_of_samples %in% merged_cluster)]
        )
        
        clusters[[cluster[1]]] = merged_cluster
        
        clusters[cluster[-1]] = NULL
        
        names(clusters) = paste0('Cluster_', 1:length(clusters))
        
        
      }else if(length(cluster) == 0 & isEmpty(proportion_of_samples_in_the_cluster)){
        cluster = length(clusters) + 1
        clusters[[paste0('Cluster_', cluster)]]  = set_of_samples
      }else if(length(cluster) == 0 & sum(proportion_of_samples_in_the_cluster == 1) == 0){
        cluster = length(clusters) + 1
        clusters[[paste0('Cluster_', cluster)]]  = set_of_samples
        
      }
      
    }
    
    
    cluster_df = NULL
    
    for(cluster in names(clusters)){
      
      cluster_name = cluster
      
      if(length(clusters[[cluster]]) == 1){
        cluster_name = gsub('Cluster', 'Singleton', cluster_name)
      }else if(length(clusters[[cluster]]) == 2){
        #cluster_name = gsub('Cluster', 'Doubleton', cluster_name)
      }else if(length(clusters[[cluster]]) == 3){
        #cluster_name = gsub('Cluster', 'Tripleton', cluster_name)
      }
      
      
      cluster_df = rbind(cluster_df, data.frame(Cluster = cluster_name, Sample_id = clusters[[cluster]]))
    }
    
    
    clusters_end = Sys.time()
    
    print('Identification of clusters took:')
    
    print(clusters_end - clusters_start)
    
    return(list(network_object = network_object,
                clusters = cluster_df))
    
  }


```



```{r 'Defining geographic distance threshold', fig.width=5, fig.height=7}

geodist = 10
increment = 10
max_geodist = 1500

rhat_formula = paste0("timedist >= 16 & timedist <= 28 & geodist <= ", geodist)

temp_cluster = get_network_clusters(pairwise_relatedness = sample_comb,
                                    variable = 'rhat',
                                    threshold = 1,
                                    cols = c("sample_i", "sample_j"),
                                    rhat_formula = rhat_formula,
                                    metadata = malaria_cases_by_person_long,
                                    sample_id = 'sample_id')

cluster_size = temp_cluster$clusters %>%
  filter(!grepl('Singleton', Cluster)) %>%
  summarise(Cluster_size = n(), .by = Cluster)  %>%
  mutate(geodist = geodist)

summary_clusters_geodist = temp_cluster$clusters %>% 
  summarise(Total = n(),
            nsampClus = sum(grepl('Cluster', Cluster)),
            nSampSing = n() - sum(grepl('Cluster', Cluster)),
            nclusters = length(unique(.$Cluster[grepl('Cluster', Cluster)]))
            
  )

summary_clusters_geodist['nNew_Clusters'] = summary_clusters_geodist['nclusters']

summary_clusters_geodist['geodist'] = geodist

temp_summary_clusters = summary_clusters_geodist

previous_clusters = temp_cluster$clusters

names(previous_clusters) = c('Old_Clusters', 'sample_id')

while(temp_summary_clusters['nclusters'] > 1 & geodist <= max_geodist
){
  geodist = geodist + increment
  rhat_formula = paste0("timedist >= 16 & timedist <= 28 & geodist <= ", geodist)
  
  temp_cluster = get_network_clusters(pairwise_relatedness = sample_comb,
                                      variable = 'rhat',
                                      threshold = 1,
                                      cols = c("sample_i", "sample_j"),
                                      rhat_formula = rhat_formula,
                                      metadata = malaria_cases_by_person_long,
                                      sample_id = 'sample_id')
  
  cluster_size = rbind(
    cluster_size, 
    temp_cluster$clusters %>%
      filter(!grepl('Singleton', Cluster)) %>%
      summarise(Cluster_size = n(), .by = Cluster)  %>%
      mutate(geodist = geodist))
  
  new_clusters = temp_cluster$clusters
  
  names(new_clusters) = c('New_Clusters', 'sample_id')
  
  previous_clusters = left_join(previous_clusters,
                                new_clusters, by = 'sample_id')
  
  
  temp_summary_clusters = temp_cluster$clusters %>% 
    summarise(Total = n(),
              nsampClus = sum(grepl('Cluster', Cluster)),
              nSampSing = n() - sum(grepl('Cluster', Cluster)),
              nclusters = length(unique(.$Cluster[grepl('Cluster', Cluster)])))
  
  temp_summary_clusters['nNew_Clusters'] = previous_clusters %>%
    filter(grepl('Cluster', New_Clusters)) %>%
    summarise(is_New_Cluster = sum(!grepl('Cluster', Old_Clusters)) == n(), .by = New_Clusters) %>%
    summarise(nNew_cluster = sum(is_New_Cluster)) %>% unlist()
  
  previous_clusters = new_clusters
  
  names(previous_clusters) = c('Old_Clusters', 'sample_id')
  
  temp_summary_clusters['geodist'] = geodist
  
  summary_clusters_geodist = rbind(summary_clusters_geodist,
                               temp_summary_clusters)
  
  
  print(geodist)
  
}


summary_clusters_geodist$deriv_nsampClus = 0
summary_clusters_geodist$deriv_nClus = 0

summary_clusters_geodist$nMerged_Clusters = 0

summary_clusters_geodist$nclusters
summary_clusters_geodist$nSampSing
summary_clusters_geodist$nsampClus

summary_clusters_geodist[-1,]$deriv_nsampClus = summary_clusters_geodist[-1,]$nsampClus - summary_clusters_geodist[-nrow(summary_clusters_geodist),]$nsampClus

summary_clusters_geodist[-1,]$deriv_nClus = summary_clusters_geodist[-1,]$nclusters - summary_clusters_geodist[-nrow(summary_clusters_geodist),]$nclusters

summary_clusters_geodist[-1,]$nMerged_Clusters = -(summary_clusters_geodist[-1,]$deriv_nClus - summary_clusters_geodist[-1,]$nNew_Clusters)


summary_clusters_geodist[1, ][['nNew_Clusters']] = 0

clusters_plot1 = summary_clusters_geodist %>% 
  # mutate(deriv_nsampClus = case_when(
  #   deriv_nsampClus < 100 ~ deriv_nsampClus,
  #   .default = NA
  # ))%>%
  pivot_longer(cols = c(nclusters,
                        deriv_nClus,
                        deriv_nsampClus,
                        nsampClus,
                        nSampSing,
                        nNew_Clusters,
                        nMerged_Clusters
  ), 
  names_to = 'Metric',
  values_to = 'Value') %>%
  mutate(Metric = case_when(
    Metric == 'nSampSing' ~ 'Number of no related samples',
    Metric == 'nsampClus' ~ 'Number of samples in clusters',
    Metric == 'deriv_nsampClus' ~ 'Number new samples added to clusters',
    Metric == 'nclusters' ~ 'Number of clusters',
    Metric == 'nNew_Clusters' ~ 'Number of new formed clusters',
    Metric == 'nMerged_Clusters' ~ 'Number of cluster merges',
    Metric == 'deriv_nClus' ~ 'Change in the number of clusters'
  )) %>%
  #filter(Metric != 'deriv_nClus')%>%
  mutate(Metric = factor(Metric, levels = c('Number of no related samples',
                                            'Number of samples in clusters',
                                            'Number new samples added to clusters',
                                            'Number of clusters',
                                            'Number of new formed clusters',
                                            'Number of cluster merges',
                                            'Change in the number of clusters'
  ))) %>% 
  filter(!Metric %in% c('Change in the number of clusters')) %>%
  ggplot(aes(x = geodist, y = Value)) + 
  geom_line() + 
  geom_vline(xintercept = c(220, 520), linetype = 2, color = 'firebrick')+
  #geom_hline(yintercept = c(0), linetype = 2, color = 'black')+
  #geom_vline(xintercept = c(.72, .75, .79, .85, .89, .91), linetype = 2, color = 'dodgerblue3') + 
  #geom_vline(xintercept = c(.59, .63, .65 , .69, .71), linetype = 2, color = 'firebrick3') + 
  facet_wrap(.~Metric, scales = 'free', ncol = 1) +
  labs(x = expression(Distance[italic(meters)])) +
  scale_x_continuous(breaks = c(seq(250, 1500, 250)))+
  theme_minimal() + 
  theme(strip.text = element_text(size = 12),
        axis.text.x = element_text(angle = 90))


clusters_plot2 = cluster_size %>%
  #filter(geodist %in% c(10, 50, 100, 150, 200, 220, 250, 300, 500, 750, 1000, 1500)) %>%
  ggplot(aes(x = geodist, y = Cluster_size)) +
  geom_point(alpha = .5) + 
  geom_vline(xintercept = c(220, 520), linetype = 2, color = 'firebrick')+
  labs(x = expression(Distance[italic(meters)]),
       y = 'Cluster size') +
  scale_x_continuous(breaks = c(seq(250, 1500, 250)))+
  theme_minimal() + 
  theme(strip.text = element_text(size = 12),
        axis.text.x = element_text(angle = 90))


ggdraw() +
  draw_plot(clusters_plot1,
            x = 0, width = 1,
            y = .30, height = .7) +
  draw_plot(clusters_plot2,
            x = 0, width = 1,
            y = 0, height = .3)





```



```{r 'Define samples that belong to clusters based on geodist (220 vs 520)'}


clusters_geodist220 = get_network_clusters(pairwise_relatedness = sample_comb,
                                           variable = 'rhat',
                                           threshold = 1,
                                           cols = c("sample_i", "sample_j"),
                                           rhat_formula = "timedist >= 16 & timedist <= 28 & geodist <= 220",
                                           metadata = malaria_cases_by_person_long,
                                           sample_id = 'sample_id')


clusters_geodist220$clusters %<>% dplyr::rename('Cluster_geodist220' = 'Cluster')

malaria_cases_by_person_long = 
  left_join(malaria_cases_by_person_long,
            clusters_geodist220$clusters,
            by = join_by('sample_id' == 'Sample_id'))


clusters_geodist520 = get_network_clusters(pairwise_relatedness = sample_comb,
                                           variable = 'rhat',
                                           threshold = 1,
                                           cols = c("sample_i", "sample_j"),
                                           rhat_formula = "timedist >= 16 & timedist <= 28 & geodist <= 520",
                                           metadata = malaria_cases_by_person_long,
                                           sample_id = 'sample_id')


clusters_geodist520$clusters %<>% dplyr::rename('Cluster_geodist520' = 'Cluster')

malaria_cases_by_person_long = 
  left_join(malaria_cases_by_person_long,
            clusters_geodist520$clusters,
            by = join_by('sample_id' == 'Sample_id'))

sample_comb %<>% 
  mutate(rhat_220 = case_when(
    timedist >= 16 & timedist <= 28 & geodist <= 220 ~ 1,
    .default = 0
    ),
    rhat_520 = case_when(
    timedist >= 16 & timedist <= 28 & geodist <= 520 ~ 1,
    .default = 0
    ))

```






```{r}

long2wide_relatedness =function(pairwise_relatedness, metadata, id, id_i, id_j, var){
  library(svMisc)
  pairwise_relatedness_l = pairwise_relatedness
  
  pairwise_relatedness_l$id_i = pairwise_relatedness_l[[id_i]]
  pairwise_relatedness_l$id_j = pairwise_relatedness_l[[id_j]]
  
  pairwise_relatedness_l %<>% filter(id_i %in% metadata[[id]],
                                     id_j %in% metadata[[id]])
  
  pairwise_relatedness_matrix = matrix(data = NA,
                                       ncol = nrow(metadata),
                                       nrow = nrow(metadata),
                                       dimnames = list(metadata[[id]],
                                                       metadata[[id]]))
  
  for(pair in 1:nrow(pairwise_relatedness_l)){
    
    pairwise_relatedness_matrix[pairwise_relatedness_l[pair,][[id_i]],
                                pairwise_relatedness_l[pair,][[id_j]]] = 
      pairwise_relatedness_l[pair,][[var]]
    
    pairwise_relatedness_matrix[pairwise_relatedness_l[pair,][[id_j]],
                                pairwise_relatedness_l[pair,][[id_i]]] = 
      0
      #pairwise_relatedness_l[pair,][[var]]
    
    progress(round(100*pair/nrow(pairwise_relatedness_l)))
  }
  
  return(pairwise_relatedness_matrix)
  
}


```

```{r}

sample_comb_matrix_220 = long2wide_relatedness(pairwise_relatedness = sample_comb, metadata = malaria_cases_by_person_long, id = 'sample_id', id_i = 'sample_i', id_j = 'sample_j', var = 'rhat_220')

sample_comb_matrix_520 = long2wide_relatedness(pairwise_relatedness = sample_comb, metadata = malaria_cases_by_person_long, id = 'sample_id', id_i = 'sample_i', id_j = 'sample_j', var = 'rhat_520')
```

```{r 'Network function'}
plot_ggnetwork = function(pairwise_relatedness_matrix = NULL,
                          metadata,
                          id,
                          color_by = NULL,
                          palette = 'Paired', 
                          shape_by = NULL,
                          shape_levels = NULL,
                          alpha_by = NULL,
                          alpha = NULL,
                          labels_by = NULL,
                          labels2paste = NULL,
                          x_displacement = 0,
                          y_displacement = 0,
                          vertex.size = 4,
                          directed = T,
                          arrow.size = 12,
                          mode = 'fruchtermanreingold'){
  
  
  library(igraph)
  if(!require(GGally)){
    install.packages("GGally")
    library(GGally)
  }else{library(GGally)}
  
  if(!require(network)){
    install.packages("network")
    library(network)
  }else{library(network)}
  
  if(!require(sna)){
    install.packages("sna")
    library(sna)
  }else{library(sna)}
  
  if(!require(ggnet)){
    devtools::install_github("briatte/ggnet")
    library(ggnet)
  }else{library(ggnet)}
  
  library(RColorBrewer)
  
  
  if(!is.null(color_by)){
    if(sum(is.na(metadata[[color_by]])) > 0){
      metadata[is.na(metadata[[color_by]]),][[color_by]] = 'missing data'
    }
  }
  
  if(!is.null(shape_by)){
    if(sum(is.na(metadata[[shape_by]])) > 0){
      metadata[is.na(metadata[[shape_by]]),][[shape_by]] = 'missing data'
    }
  }
  
  
  if(!is.null(alpha_by)){
    if(sum(is.na(metadata[[alpha_by]])) > 0){
      metadata[is.na(metadata[[alpha_by]]),][[alpha_by]] = 'missing data'
    }
  }
  
  
  
  relatedness_network = network(pairwise_relatedness_matrix, directed = directed)
  
  network.vertex.names(relatedness_network) = metadata[[id]]
  
  
  if(!is.null(color_by)){
    relatedness_network %v% color_by = as.character(metadata[[color_by]])
  }else{
    color_by = 'gray75'
  }
  
  if(!is.null(shape_by)){
    
    if(!is.null(shape_levels)){
      relatedness_network %v% shape_by = factor(metadata[[shape_by]], levels = shape_levels)
    }else{
      relatedness_network %v% shape_by = as.character(metadata[[shape_by]])  
    }
      
  }else{
    shape_by = 16
  }
  
  if(!is.null(alpha_by)){
    relatedness_network %v% alpha_by = as.character(metadata[[alpha_by]])
  }else if(!is.null(alpha)){
    alpha_by = alpha
  }else{
    alpha_by = 1
  }
  
  if('AUTO' %in% toupper(palette)){
    
    qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
    col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
    
    palette = col_vector[1:length(unique(metadata[[color_by]]))]
    
  }
  
  if(length(palette) > 1){
    
    plot_network = ggnet2(relatedness_network,
                          size = vertex.size,
                          color = color_by,
                          #color.palette = color_palette,
                          shape = shape_by,
                          #palette = 'Paired',
                          #color.label = TRUE,
                          arrow.size = arrow.size,
                          alpha = alpha_by,
                          mode = mode)
    
    
    plot_network = plot_network +
      scale_color_manual(values = palette)
    
  }else{
    
    plot_network = ggnet2(relatedness_network,
                          size = vertex.size,
                          color = color_by,
                          #color.palette = color_palette,
                          shape = shape_by,
                          palette = palette,
                          #color.label = TRUE,
                          arrow.size = arrow.size,
                          alpha = alpha_by,
                          mode = mode)
    
  }
  
  # Adding Labels
  
  if(!is.null(labels_by) & !is.null(labels2paste)){
    
    xcoord = NULL
    
    ycoord = NULL
    
    for(label2paste in labels2paste){
      
      xcoord = c(xcoord,
                 mean(plot_network@data[['x']][
                   plot_network@data[['label']] %in% 
                     metadata[[id]][metadata[[labels_by]] == label2paste]])
        )
      
      ycoord = c(ycoord,
                 mean(plot_network@data[['y']][
                   plot_network@data[['label']] %in% 
                     metadata[[id]][metadata[[labels_by]] == label2paste]])
      )
      
    }
    
    plot_network = 
      plot_network +
      annotate(geom = 'text',
               x = xcoord + x_displacement,
               y = ycoord + y_displacement,
               label = labels2paste,
               fontface = 'bold'
               )
    
    
  }
  
  return(list(network_object = relatedness_network,
              plot_network = plot_network))
  
}
```


```{r 'Define cluster to plot'}

malaria_cases_by_person_long %>%
  summarise(nSamples = n(),
            .by = c(Cluster_geodist220, Cluster_geodist520, village)
            ) %>%
  arrange(desc(nSamples)) %>% View()

```




```{r}


qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
    
palette = col_vector[1:length(unique(malaria_cases_by_person_long[['year_quarter']]))]
set.seed(5)
transmission_network_220_bytime = plot_ggnetwork(pairwise_relatedness_matrix = sample_comb_matrix_220, 
                                      metadata = malaria_cases_by_person_long, 
                                      color_by = 'year_quarter', 
                                      palette = palette, 
                                      id = 'sample_id',
                                      directed = T,
                                      labels_by = 'Cluster_geodist220',
                                      labels2paste = c('Cluster_14', 'Cluster_12', 'Cluster_19', 'Cluster_2'),
                                      arrow.size = 4,
                                      vertex.size = 2.5
                                      )

set.seed(5)
transmission_network_220_byvillage = plot_ggnetwork(pairwise_relatedness_matrix = sample_comb_matrix_220, 
                                      metadata = malaria_cases_by_person_long, 
                                      color_by = 'village', 
                                      palette = palette, 
                                      id = 'sample_id',
                                      directed = T,
                                      labels_by = 'Cluster_geodist220',
                                      labels2paste = c('Cluster_14', 'Cluster_12', 'Cluster_19', 'Cluster_2'),
                                      arrow.size = 4,
                                      vertex.size = 2.5
                                      )



```

```{r, fig.width=10, fig.height=10}
install.packages('lubridate')
library(lubridate)


malaria_cases_by_person_long %<>% 
  mutate(week = week(as.Date(date)))

plot_incidence = malaria_cases_by_person_long %>%
  filter(village_id == '07') %>%
  summarise(nCases = n(), .by = c(year_quarter, week)) %>%
  mutate(year = gsub('-.+$', '', year_quarter),
         quarter = gsub('^.+-', '', year_quarter)) %>%
  ggplot(aes(x = week, y = nCases, fill = year_quarter)) +
  geom_col() +
  facet_grid(.~ year) + 
  scale_fill_manual(values = palette) +
  labs(y = 'Cases', x = 'Week') +
  theme_minimal() +
  theme(legend.position = 'none')

ggdraw()+
  draw_plot(plot_incidence,
            x = 0, width = 1,
            y = .75, height = .25) +
  draw_plot(transmission_network_220_byvillage$plot_network +
              theme(legend.position = 'bottom',
                    legend.title.position = 'top',
                    legend.text = element_text(size = 6)) + 
    labs(color = 'Village') +
    guides(color = guide_legend(nrow = 6,
                                override.aes = list(size = 2))),
    x = 0, width = .5,
    y = 0, height = .75) +
  draw_plot(transmission_network_220_bytime$plot_network +
              theme(legend.position = 'bottom',
                    legend.title.position = 'top') + 
    labs(color = 'Year quarter') +
    guides(color = guide_legend(nrow = 6,
                                override.aes = list(size = 2))),
    x = .5, width = .5,
    y = 0, height = .75)

```

```{r}


qual_col_pals = brewer.pal.info[brewer.pal.info$category == 'qual',]
col_vector = unlist(mapply(brewer.pal, qual_col_pals$maxcolors, rownames(qual_col_pals)))
    
palette = col_vector[1:length(unique(malaria_cases_by_person_long[['year_quarter']]))]
set.seed(5)
transmission_network_520_bytime = plot_ggnetwork(pairwise_relatedness_matrix = sample_comb_matrix_520, 
                                      metadata = malaria_cases_by_person_long, 
                                      color_by = 'year_quarter', 
                                      palette = palette, 
                                      id = 'sample_id',
                                      directed = T,
                                      labels_by = 'Cluster_geodist220',
                                      labels2paste = c('Cluster_14', 'Cluster_12', 'Cluster_19', 'Cluster_2'),
                                      arrow.size = 4,
                                      vertex.size = 2.5
                                      )

set.seed(5)
transmission_network_520_byvillage = plot_ggnetwork(pairwise_relatedness_matrix = sample_comb_matrix_520, 
                                      metadata = malaria_cases_by_person_long, 
                                      color_by = 'village', 
                                      palette = palette, 
                                      id = 'sample_id',
                                      directed = T,
                                      labels_by = 'Cluster_geodist220',
                                      labels2paste = c('Cluster_14', 'Cluster_12', 'Cluster_19', 'Cluster_2'),
                                      arrow.size = 4,
                                      vertex.size = 2.5
                                      )



```

```{r, fig.width=10, fig.height=10}


ggdraw()+
  draw_plot(plot_incidence,
            x = 0, width = 1,
            y = .75, height = .25) +
  draw_plot(transmission_network_520_byvillage$plot_network +
              theme(legend.position = 'bottom',
                    legend.title.position = 'top',
                    legend.text = element_text(size = 6)) + 
    labs(color = 'Village') +
    guides(color = guide_legend(nrow = 6,
                                override.aes = list(size = 2))),
    x = 0, width = .5,
    y = 0, height = .75) +
  draw_plot(transmission_network_520_bytime$plot_network +
              theme(legend.position = 'bottom',
                    legend.title.position = 'top') + 
    labs(color = 'Year quarter') +
    guides(color = guide_legend(nrow = 6,
                                override.aes = list(size = 2))),
    x = .5, width = .5,
    y = 0, height = .75)

```


```{r}
sample_comb %>% 
  filter(rhat_520 == 1) %>%
  summarise(nSecCases = length(unique(sample_i)), .by = hh_i) %>% arrange(desc(nSecCases))
```









```{r 'Community layer'}
# library(cowplot)
# 
# install.packages('OpenStreetMap')
# library(OpenStreetMap)

max_long07 = malaria_cases_by_person_long %>%
  filter(village_id == '07') %>%
  select(longitude) %>%
  unlist() %>%
  max()

min_long07 = malaria_cases_by_person_long %>%
  filter(village_id == '07') %>%
  select(longitude) %>%
  unlist() %>%
  min()

max_latd07 = malaria_cases_by_person_long %>%
  filter(village_id == '07') %>%
  select(latitude) %>%
  unlist() %>%
  max()

min_latd07 = malaria_cases_by_person_long %>%
  filter(village_id == '07') %>%
  select(latitude) %>%
  unlist() %>%
  min()

osm_07 <- openmap(c(min_latd07 - 0.001, min_long07 - 0.001), 
                    c(max_latd07 + 0.001, max_long07 + 0.001), 
                    zoom = NULL,
                    type = "osm", 
                    mergeTiles = TRUE)

osm_07 <- openproj(osm_07, projection = "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs")

```

```{r 'Potential to generate secondary cases or being a secondary case', fig.width=5, fig.height=5}
plot1 =  autoplot.OpenStreetMap(osm_07, alpha =.5) + 
  geom_point(data = sample_comb %>%
          filter(relatedness == 1 & scale == 'Within' & village_id_i == '07'
                 ),
         aes(x = long_i, y = lat_i), shape = 16, alpha = .025, size = 2.5) +
  theme_minimal()

plot2 =  autoplot.OpenStreetMap(osm_07, alpha =.5) + 
  geom_point(data = sample_comb %>%
          filter(relatedness == 1 & scale == 'Within' & village_id_i == '07'
                 ),
         aes(x = long_j, y = lat_j), shape = 17, alpha = .025, size = 2.5) +
  theme_minimal()


ggdraw() +
  draw_plot(plot1,
            x = 0, width = 1,
            y = .5, height = .5) +
  draw_plot(plot2,
            x = 0, width = 1,
            y = 0, height = .5)

```

```{r, fig.width= 8, fig.height=8}
install.packages('ggspatial')
library(ggspatial)
autoplot.OpenStreetMap(osm_07) +
  annotation_scale() + 
  geom_point(data = sample_comb %>% 
          filter(relatedness == 1 & scale == 'Within' & village_id_i == '07'
                 ),
         aes(x = long_i, y = lat_i), shape = 16, alpha = .025) +
  geom_segment(data = sample_comb %>% 
          filter(relatedness == 1 & scale == 'Within' & village_id_i == '07'
                 ), aes(x = long_i, y = lat_i, xend = long_j, yend = lat_j), arrow = arrow(length = unit(0.1, "cm")), alpha = .01)+
  geom_point(data = sample_comb %>% 
               filter(relatedness == 1 & scale == 'Within' & village_id_i == '07'
                      ),
             aes(x = long_j, y = lat_j), shape = 17, alpha = .025)

```



